# Generated by Django 4.1.13 on 2025-12-13 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area_m2', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='land_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pv_efficiency', models.FloatField(default=0.2)),
                ('pv_performance_ratio', models.FloatField(default=0.8)),
                ('pv_land_coverage', models.FloatField(default=0.6)),
                ('pv_system_efficiency', models.FloatField(default=0.95)),
                ('wind_rated_power_kw', models.FloatField(default=5.0)),
                ('wind_rotor_diameter_m', models.FloatField(default=7.0)),
                ('wind_hub_height_m', models.FloatField(default=20.0)),
                ('wind_cut_in_ms', models.FloatField(default=3.0)),
                ('wind_rated_ws_ms', models.FloatField(default=12.0)),
                ('wind_cut_out_ms', models.FloatField(default=25.0)),
                ('wind_alpha', models.FloatField(default=0.14)),
                ('wind_system_efficiency', models.FloatField(default=0.9)),
                ('dc_voltage', models.FloatField(default=48.0)),
                ('soil_data', models.JSONField(blank=True, null=True)),
                ('crop_recommendations', models.JSONField(blank=True, null=True)),
                ('energy_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='potential_app.land')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('landowner', 'Landowner'), ('builder', 'PV Plant Builder')], default='landowner', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message from Landowner to Builder')),
                ('builder_response_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_builder', 'Pending Builder Review'), ('accepted', 'Accepted by Builder'), ('rejected', 'Rejected by Builder'), ('negotiating', 'Negotiating'), ('finalized', 'Finalized')], default='pending_builder', max_length=20)),
                ('investment_choice', models.CharField(choices=[('pending', 'Pending Decision'), ('self_invest', 'Landowner Invests (Full Ownership)'), ('builder_invest', 'Builder Invests (Lease/Transfer Model)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL)),
                ('land_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='potential_app.landanalysis')),
                ('landowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent_by_landowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuilderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Describe your company and solar plans.')),
                ('experience_years', models.IntegerField(default=0)),
                ('portfolio_images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('customer_reviews', models.JSONField(blank=True, default=list, help_text='List of review objects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('signed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bond', to='potential_app.proposal')),
            ],
        ),
    ]
