# Generated by Django 5.2.5 on 2025-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pv_efficiency', models.FloatField(default=0.2)),
                ('pv_performance_ratio', models.FloatField(default=0.8)),
                ('pv_land_coverage', models.FloatField(default=0.6)),
                ('pv_system_efficiency', models.FloatField(default=0.95)),
                ('wind_rated_power_kw', models.FloatField(default=5.0)),
                ('wind_rotor_diameter_m', models.FloatField(default=7.0)),
                ('wind_hub_height_m', models.FloatField(default=20.0)),
                ('wind_cut_in_ms', models.FloatField(default=3.0)),
                ('wind_rated_ws_ms', models.FloatField(default=12.0)),
                ('wind_cut_out_ms', models.FloatField(default=25.0)),
                ('wind_alpha', models.FloatField(default=0.14)),
                ('wind_system_efficiency', models.FloatField(default=0.9)),
                ('dc_voltage', models.FloatField(default=48.0)),
                ('soil_data', models.JSONField(blank=True, null=True)),
                ('crop_recommendations', models.JSONField(blank=True, null=True)),
                ('energy_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
